$axure.loadCurrentPage({
  "url":"tea_index.html",
  "generationDate":new Date(1528272927022.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0d78b14229e34291a7d80ded8905779c",
    "type":"Axure:Page",
    "name":"tea_index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"35b4fdcfe4584f8398b2285895c2a215",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e01321d315b40cfb14125bdabe4e564",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"241ecc5edc9644caa823c426bef7785c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":603.5,
              "y":31.5},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ea5b2e741f42809f90fc6d0dc6ea9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603.5,
                  "y":31.5},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e5f52a1fa204ce78400db7feb6f6543",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":210},
            "size":{
              "width":100,
              "height":135}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2841976a6574692bc8c026416dbee5a",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":135}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25cb2cb96c4e40ed807627680be0d665",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":47}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb766e25bd01454280566180daa0d82b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":47}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/stu_index/u6.png"}},
{
                  "id":"8974c95dbe7743b69fd741f89f5d7ad0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":47},
                    "size":{
                      "width":100,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1589fc8f40d44ca38dc1813801e0619d",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":47},
                        "size":{
                          "width":100,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/stu_index/u10.png"}},
{
                  "id":"abbdcbb24fe546e8a3f7b62428730941",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":91},
                    "size":{
                      "width":100,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ddc19a07ca345e088a28cb35f40f52b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":91},
                        "size":{
                          "width":100,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/stu_index/u12.png"}}]},
{
              "id":"a14aac4a3f594246b215fdfcf799a86f",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":47},
                "size":{
                  "width":100,
                  "height":44},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8004e4716286426788b59a80c65e48b9",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2c0f7a91f744bc6b2dbc7e40c5c3f05",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":44},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c8be94683e804e67a691533c48b872e8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":44},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u12.png"}}]}],
              "parentCellId":"8974c95dbe7743b69fd741f89f5d7ad0"},
{
              "id":"99effc410f0c489fbad50fbc92dd9b4e",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":132},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f032e5b6a80745ccb6be29be85062766",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":132}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33e09881fbfb48709040d7e2045c6de4",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":46},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c79cf637f57a431fa617801b74e78270",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":46},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u22.png"}},
{
                      "id":"b4c0b98c03b241478d220f973c217483",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":100,
                          "height":43},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d65a001a0c544ae298910872041e636b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":100,
                              "height":43},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u24.png"}},
{
                      "id":"7cd38545d78a4fd7951d354f4582fdc2",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":89},
                        "size":{
                          "width":100,
                          "height":43},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1c4d6075a0954aed9e5c29abc472658e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":89},
                            "size":{
                              "width":100,
                              "height":43},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u26.png"}}]}],
              "parentCellId":"25cb2cb96c4e40ed807627680be0d665"},
{
              "id":"371ee61ef81945dc94c69e1a03a65be1",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":91},
                "size":{
                  "width":100,
                  "height":86},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc3822158f2c4c5980d11ee5392f0940",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":86}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e44587c7205448bdb6392adbf38c7c20",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":43},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"95143ba0edf041ac8d3becfeb6e57935",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":43},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u24.png"}},
{
                      "id":"6b55a61092a648a482ede4572e059ec5",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":43},
                        "size":{
                          "width":100,
                          "height":43},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3d79d3ab39464c0b9771704fcd8eeb66",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":43},
                            "size":{
                              "width":100,
                              "height":43},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u26.png"}}]}],
              "parentCellId":"abbdcbb24fe546e8a3f7b62428730941"}]},
{
          "id":"9a342fd0b02346f1a18f622a19b0b5cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f4ec90ce514acaad5f882e0b7676f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"c179b60ce2d24a17a3bab64ad6afc930",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b714630e25f1470faa6bbaff593b6efa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"476ba51b6bce423aa50c86bad2dca817",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "35b4fdcfe4584f8398b2285895c2a215":{
      "scriptId":"u0"},
    "0e01321d315b40cfb14125bdabe4e564":{
      "scriptId":"u1"},
    "241ecc5edc9644caa823c426bef7785c":{
      "scriptId":"u2"},
    "d2ea5b2e741f42809f90fc6d0dc6ea9f":{
      "scriptId":"u3"},
    "2e5f52a1fa204ce78400db7feb6f6543":{
      "scriptId":"u4"},
    "d2841976a6574692bc8c026416dbee5a":{
      "scriptId":"u5"},
    "25cb2cb96c4e40ed807627680be0d665":{
      "scriptId":"u6"},
    "eb766e25bd01454280566180daa0d82b":{
      "scriptId":"u7"},
    "8974c95dbe7743b69fd741f89f5d7ad0":{
      "scriptId":"u8"},
    "1589fc8f40d44ca38dc1813801e0619d":{
      "scriptId":"u9"},
    "abbdcbb24fe546e8a3f7b62428730941":{
      "scriptId":"u10"},
    "9ddc19a07ca345e088a28cb35f40f52b":{
      "scriptId":"u11"},
    "a14aac4a3f594246b215fdfcf799a86f":{
      "scriptId":"u12"},
    "8004e4716286426788b59a80c65e48b9":{
      "scriptId":"u13"},
    "a2c0f7a91f744bc6b2dbc7e40c5c3f05":{
      "scriptId":"u14"},
    "c8be94683e804e67a691533c48b872e8":{
      "scriptId":"u15"},
    "99effc410f0c489fbad50fbc92dd9b4e":{
      "scriptId":"u16"},
    "f032e5b6a80745ccb6be29be85062766":{
      "scriptId":"u17"},
    "33e09881fbfb48709040d7e2045c6de4":{
      "scriptId":"u18"},
    "c79cf637f57a431fa617801b74e78270":{
      "scriptId":"u19"},
    "b4c0b98c03b241478d220f973c217483":{
      "scriptId":"u20"},
    "d65a001a0c544ae298910872041e636b":{
      "scriptId":"u21"},
    "7cd38545d78a4fd7951d354f4582fdc2":{
      "scriptId":"u22"},
    "1c4d6075a0954aed9e5c29abc472658e":{
      "scriptId":"u23"},
    "371ee61ef81945dc94c69e1a03a65be1":{
      "scriptId":"u24"},
    "bc3822158f2c4c5980d11ee5392f0940":{
      "scriptId":"u25"},
    "e44587c7205448bdb6392adbf38c7c20":{
      "scriptId":"u26"},
    "95143ba0edf041ac8d3becfeb6e57935":{
      "scriptId":"u27"},
    "6b55a61092a648a482ede4572e059ec5":{
      "scriptId":"u28"},
    "3d79d3ab39464c0b9771704fcd8eeb66":{
      "scriptId":"u29"},
    "9a342fd0b02346f1a18f622a19b0b5cf":{
      "scriptId":"u30"},
    "d8f4ec90ce514acaad5f882e0b7676f6":{
      "scriptId":"u31"},
    "c179b60ce2d24a17a3bab64ad6afc930":{
      "scriptId":"u32"},
    "b714630e25f1470faa6bbaff593b6efa":{
      "scriptId":"u33"},
    "476ba51b6bce423aa50c86bad2dca817":{
      "scriptId":"u34"}}});