$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1528272926922.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8b1ddfc3232c40c2bd85f97039bf0977",
    "type":"Axure:Page",
    "name":"login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cd3d58b61f5b42fb8e1ac4538fedf2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2a287f466bb465e82acb06423630514",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"c677d9104a83430f805b41b69b837316",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":603.5,
              "y":31.5},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bcae1b265124e60956025d735108af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603.5,
                  "y":31.5},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd665a4ddcc44aaab15bb26a85c0c0bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":487.5,
              "y":170},
            "size":{
              "width":425,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bae138a95844f04b04288d672b8a049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":487.5,
                  "y":170},
                "size":{
                  "width":425,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u4.png"}},
{
          "id":"25d81f2ead6e4e46a6b9c8b7b9c8be9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":662,
              "y":200},
            "size":{
              "width":78,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6666589415d4adca2000fdfe95fef8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":662,
                  "y":200},
                "size":{
                  "width":78,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a48e94feba244ccb89528ac2f46934b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":510,
              "y":300},
            "size":{
              "width":90,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae7edd91af454d43a7349dcf14ee56a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":510,
                  "y":300},
                "size":{
                  "width":90,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u8.png"}},
{
          "id":"78f1d1babea14c6dad119b30e02c8c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":510,
              "y":370},
            "size":{
              "width":90,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68960b0d479843878d63dfab1616b71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":510,
                  "y":370},
                "size":{
                  "width":90,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u8.png"}},
{
          "id":"aadbd2b9d77447669f900abb4354354e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":305},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2dc6d92827774d78b3d4cfe2e22aee9f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":375},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b437f1572ad04da5adf7e70d95a869df",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":454},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f83ab413dcd4328abd30f2a5e45c85a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":454},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c438238089094cd5a5dc744a8efaedd1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":454},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a47fe0be68b4c069c75610f44303de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":454},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"befee1c8f62c4e859110a66e72fc7d41",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":515},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d0b3c80553f948918dc5c31e0a884e83",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":515},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "cd3d58b61f5b42fb8e1ac4538fedf2ab":{
      "scriptId":"u0"},
    "d2a287f466bb465e82acb06423630514":{
      "scriptId":"u1"},
    "c677d9104a83430f805b41b69b837316":{
      "scriptId":"u2"},
    "4bcae1b265124e60956025d735108af4":{
      "scriptId":"u3"},
    "fd665a4ddcc44aaab15bb26a85c0c0bf":{
      "scriptId":"u4"},
    "1bae138a95844f04b04288d672b8a049":{
      "scriptId":"u5"},
    "25d81f2ead6e4e46a6b9c8b7b9c8be9a":{
      "scriptId":"u6"},
    "e6666589415d4adca2000fdfe95fef8a":{
      "scriptId":"u7"},
    "0a48e94feba244ccb89528ac2f46934b":{
      "scriptId":"u8"},
    "ae7edd91af454d43a7349dcf14ee56a4":{
      "scriptId":"u9"},
    "78f1d1babea14c6dad119b30e02c8c4b":{
      "scriptId":"u10"},
    "68960b0d479843878d63dfab1616b71d":{
      "scriptId":"u11"},
    "aadbd2b9d77447669f900abb4354354e":{
      "scriptId":"u12"},
    "2dc6d92827774d78b3d4cfe2e22aee9f":{
      "scriptId":"u13"},
    "b437f1572ad04da5adf7e70d95a869df":{
      "scriptId":"u14"},
    "5f83ab413dcd4328abd30f2a5e45c85a":{
      "scriptId":"u15"},
    "c438238089094cd5a5dc744a8efaedd1":{
      "scriptId":"u16"},
    "2a47fe0be68b4c069c75610f44303de2":{
      "scriptId":"u17"},
    "befee1c8f62c4e859110a66e72fc7d41":{
      "scriptId":"u18"},
    "d0b3c80553f948918dc5c31e0a884e83":{
      "scriptId":"u19"}}});