$axure.loadCurrentPage({
  "url":"set_password.html",
  "generationDate":new Date(1528272927165.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e7015f52b2b4025be0d2061a4abf92a",
    "type":"Axure:Page",
    "name":"set_password",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a24541473d174d6f85ba9c8796b1bf9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34da3add8d334295931c93fb362bf420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"0cd588af688342c7a862e287a30dc219",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":32},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"258317a59ae644a5b2ab133dfdf4ea32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":32},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d96c88e039549f1a0ff4af601f66a24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49930efaedbb4ea697fd8862aa83f706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"c9bf62ce398c4cd48a63947c877f0cef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e59fac93094261a0eb85f02c139ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adf3052bf88e41e5876381d7aff1bc20",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"a87d72e351854844bb0fcd04254baaea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":210},
            "size":{
              "width":600,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f644ca0928a46b9aa7b944036daf6f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":210},
                "size":{
                  "width":600,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/set_password/u9.png"}},
{
          "id":"a5869cb7f9e741bebf140d78f9ecfa2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":230},
            "size":{
              "width":120,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ec2eaf8d0147599ca3c1fcb8b7cb3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":230},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/set_password/u11.png"}},
{
          "id":"db05660b19cc43d2bd76d96db604d6ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":280},
            "size":{
              "width":120,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efc991a5657441baad780df62a579f6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":280},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/set_password/u11.png"}},
{
          "id":"b4be29d0c11f47b88c4051611384e617",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":330},
            "size":{
              "width":120,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deda56e4f90d4962bac2765d32f7031a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":330},
                "size":{
                  "width":120,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/set_password/u11.png"}},
{
          "id":"7dc1c456618e46689a42ef10bfd0dcaf",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":230},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"c47b6a6420474759a00eb9072ca55ec2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":280},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"be41ca8c11374bf3ba8cb3cb1491584f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":330},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"bd28c161a82f4f47b905106cac1e70b3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":405},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"92ea9c4e89a54395a05f1ecccf5f8320",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":405},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "a24541473d174d6f85ba9c8796b1bf9c":{
      "scriptId":"u0"},
    "34da3add8d334295931c93fb362bf420":{
      "scriptId":"u1"},
    "0cd588af688342c7a862e287a30dc219":{
      "scriptId":"u2"},
    "258317a59ae644a5b2ab133dfdf4ea32":{
      "scriptId":"u3"},
    "6d96c88e039549f1a0ff4af601f66a24":{
      "scriptId":"u4"},
    "49930efaedbb4ea697fd8862aa83f706":{
      "scriptId":"u5"},
    "c9bf62ce398c4cd48a63947c877f0cef":{
      "scriptId":"u6"},
    "35e59fac93094261a0eb85f02c139ed9":{
      "scriptId":"u7"},
    "adf3052bf88e41e5876381d7aff1bc20":{
      "scriptId":"u8"},
    "a87d72e351854844bb0fcd04254baaea":{
      "scriptId":"u9"},
    "9f644ca0928a46b9aa7b944036daf6f0":{
      "scriptId":"u10"},
    "a5869cb7f9e741bebf140d78f9ecfa2e":{
      "scriptId":"u11"},
    "b1ec2eaf8d0147599ca3c1fcb8b7cb3c":{
      "scriptId":"u12"},
    "db05660b19cc43d2bd76d96db604d6ed":{
      "scriptId":"u13"},
    "efc991a5657441baad780df62a579f6e":{
      "scriptId":"u14"},
    "b4be29d0c11f47b88c4051611384e617":{
      "scriptId":"u15"},
    "deda56e4f90d4962bac2765d32f7031a":{
      "scriptId":"u16"},
    "7dc1c456618e46689a42ef10bfd0dcaf":{
      "scriptId":"u17"},
    "c47b6a6420474759a00eb9072ca55ec2":{
      "scriptId":"u18"},
    "be41ca8c11374bf3ba8cb3cb1491584f":{
      "scriptId":"u19"},
    "bd28c161a82f4f47b905106cac1e70b3":{
      "scriptId":"u20"},
    "92ea9c4e89a54395a05f1ecccf5f8320":{
      "scriptId":"u21"}}});