$axure.loadCurrentPage({
  "url":"stu_index.html",
  "generationDate":new Date(1528272926982.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3222b638fc814b528f5b5848caa17d1f",
    "type":"Axure:Page",
    "name":"stu_index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ece08fc39a3940d7b3da6f234b3ccbca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d69dd4a968444d9db4ecf28c1020b549",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"e76c69b9910c41069ca79510ba68ae6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":603.5,
              "y":31.5},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b529eed0cf041aaa20f872e755c65ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":603.5,
                  "y":31.5},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a95f3ac26b0a40aeb86e0921b17aa35d",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":210},
            "size":{
              "width":100,
              "height":177}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97e1fd61d90e491f8ffb4139def84eea",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":177}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71a8c3cbfcfb48f49146593d82b5a229",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":47}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"31be3e97cc5a4c3a9e4d4384906543c3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":47}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/stu_index/u6.png"}},
{
                  "id":"bc9bb70ddcb84ca5be008431c7607f29",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":47},
                    "size":{
                      "width":100,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"accd55ebc2864edd9a8e02a60e488029",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":47},
                        "size":{
                          "width":100,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/stu_index/u8.png"}},
{
                  "id":"8239060cb7b14fa584c37cf1de8c716e",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":89},
                    "size":{
                      "width":100,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"943d245244dd42e4b4c134ea55a259d4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":89},
                        "size":{
                          "width":100,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/stu_index/u10.png"}},
{
                  "id":"a6d1ccf27ce64e80b3ef9f55cb074aa3",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":0,
                      "y":133},
                    "size":{
                      "width":100,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0117b4c8c8384379befc56ffc84bad90",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":133},
                        "size":{
                          "width":100,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/stu_index/u12.png"}}]},
{
              "id":"b1b983341ea64e259ca55d1d7bd058ec",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":89},
                "size":{
                  "width":100,
                  "height":88},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"773f800d8513406bab2d295ec76702be",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":88}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"514aa5982d7e48ddb6b130f7a330037d",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":44},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b774502785144a5fa91bd7fb460afcc6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":44},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u10.png"}},
{
                      "id":"e03c2846caa24f69a46f6206420226b9",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":44},
                        "size":{
                          "width":100,
                          "height":44},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b5a80648b265439eb3a101344832c0a3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":44},
                            "size":{
                              "width":100,
                              "height":44},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u12.png"}}]}],
              "parentCellId":"8239060cb7b14fa584c37cf1de8c716e"},
{
              "id":"a488f72be7a242ee8f9afbab0e5ff805",
              "label":"",
              "type":"menuObject",
              "styleType":"menuObject",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":132},
                "limbo":false},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d1494949176748d9b1e0633c6069e067",
                  "label":"",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":132}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"95958515b94a4deba68827cafbe97334",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":46},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f14e818615c84e23b257048c229eb76b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "size":{
                              "width":100,
                              "height":46},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u22.png"}},
{
                      "id":"8ff360ff40134582a990ad44ba81075e",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":46},
                        "size":{
                          "width":100,
                          "height":43},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d38faf653ca64a8f9fdf3c10ed5a59ff",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":46},
                            "size":{
                              "width":100,
                              "height":43},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u24.png"}},
{
                      "id":"546d8e2e472b44889f3bd2e4761c9f83",
                      "label":"",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":0,
                          "y":89},
                        "size":{
                          "width":100,
                          "height":43},
                        "limbo":false},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a4b0123534b9464a8c244ed4ebc2ba2a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFFF},
                            "location":{
                              "x":0,
                              "y":89},
                            "size":{
                              "width":100,
                              "height":43},
                            "limbo":false},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/stu_index/u26.png"}}]}],
              "parentCellId":"71a8c3cbfcfb48f49146593d82b5a229"}]},
{
          "id":"bf4a1fbdb263458cb9856cb3f8788e92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd987e78ee84a34b14e19a1540b0415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"08ba0c7aac354660b9a6462f73da402f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4079b0b841143449235d4d319d9b71c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c351edc248e64645b676292b7f9878f9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "ece08fc39a3940d7b3da6f234b3ccbca":{
      "scriptId":"u0"},
    "d69dd4a968444d9db4ecf28c1020b549":{
      "scriptId":"u1"},
    "e76c69b9910c41069ca79510ba68ae6b":{
      "scriptId":"u2"},
    "0b529eed0cf041aaa20f872e755c65ec":{
      "scriptId":"u3"},
    "a95f3ac26b0a40aeb86e0921b17aa35d":{
      "scriptId":"u4"},
    "97e1fd61d90e491f8ffb4139def84eea":{
      "scriptId":"u5"},
    "71a8c3cbfcfb48f49146593d82b5a229":{
      "scriptId":"u6"},
    "31be3e97cc5a4c3a9e4d4384906543c3":{
      "scriptId":"u7"},
    "bc9bb70ddcb84ca5be008431c7607f29":{
      "scriptId":"u8"},
    "accd55ebc2864edd9a8e02a60e488029":{
      "scriptId":"u9"},
    "8239060cb7b14fa584c37cf1de8c716e":{
      "scriptId":"u10"},
    "943d245244dd42e4b4c134ea55a259d4":{
      "scriptId":"u11"},
    "a6d1ccf27ce64e80b3ef9f55cb074aa3":{
      "scriptId":"u12"},
    "0117b4c8c8384379befc56ffc84bad90":{
      "scriptId":"u13"},
    "b1b983341ea64e259ca55d1d7bd058ec":{
      "scriptId":"u14"},
    "773f800d8513406bab2d295ec76702be":{
      "scriptId":"u15"},
    "514aa5982d7e48ddb6b130f7a330037d":{
      "scriptId":"u16"},
    "b774502785144a5fa91bd7fb460afcc6":{
      "scriptId":"u17"},
    "e03c2846caa24f69a46f6206420226b9":{
      "scriptId":"u18"},
    "b5a80648b265439eb3a101344832c0a3":{
      "scriptId":"u19"},
    "a488f72be7a242ee8f9afbab0e5ff805":{
      "scriptId":"u20"},
    "d1494949176748d9b1e0633c6069e067":{
      "scriptId":"u21"},
    "95958515b94a4deba68827cafbe97334":{
      "scriptId":"u22"},
    "f14e818615c84e23b257048c229eb76b":{
      "scriptId":"u23"},
    "8ff360ff40134582a990ad44ba81075e":{
      "scriptId":"u24"},
    "d38faf653ca64a8f9fdf3c10ed5a59ff":{
      "scriptId":"u25"},
    "546d8e2e472b44889f3bd2e4761c9f83":{
      "scriptId":"u26"},
    "a4b0123534b9464a8c244ed4ebc2ba2a":{
      "scriptId":"u27"},
    "bf4a1fbdb263458cb9856cb3f8788e92":{
      "scriptId":"u28"},
    "3cd987e78ee84a34b14e19a1540b0415":{
      "scriptId":"u29"},
    "08ba0c7aac354660b9a6462f73da402f":{
      "scriptId":"u30"},
    "a4079b0b841143449235d4d319d9b71c":{
      "scriptId":"u31"},
    "c351edc248e64645b676292b7f9878f9":{
      "scriptId":"u32"}}});