$axure.loadCurrentPage({
  "url":"search_course.html",
  "generationDate":new Date(1528272927335.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b1dd1b2e8b7b4ef8be989cc79dbba8eb",
    "type":"Axure:Page",
    "name":"search_course",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"71774aee331145c7a618dcb567e2c1a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4c9cb5db974088b7b78bdeec30ad22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"6d6a21c0cb8f4d43ac8d9aed73ca5014",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":32},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d21fcf76ed6a4ce2a9d897c50561d895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":32},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9260faaec67d4fb28f3c9a338fbf893f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"416b8f194c174fe4a2b623ab5e6ad9bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"563ba3247d4347359f15a5ad415e6b6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c373f42e54b428c977c15ebe65a9ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b18ce2eb11c4890a21aef6f0743b683",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"cd1b884809624d55b21c1967e97077e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":210},
            "size":{
              "width":650,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db18cdbdd03d461d94ad863ddd42bf73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":210},
                "size":{
                  "width":650,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_course/u9.png"}},
{
          "id":"208d7a6d8ddf48e6b567ca535be57a69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":228},
            "size":{
              "width":130,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60565e2f791d49c0b85e68c8528f8852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":228},
                "size":{
                  "width":130,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_course/u11.png"}},
{
          "id":"a3c210d689844f1699bd627c1de15827",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":228},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"9dee6b7d59e142d48ad012dfd58a3ac9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":280},
            "size":{
              "width":650,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search_course/u14_line.png"}},
{
          "id":"05f4dd151b704e7bbab2d8a27385e9ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":310},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2340bc73302b49748c6af285b57684ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":310},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_course/u15.png"}},
{
          "id":"3eaa9cfb4687463497b36b1b015e78a3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":310},
            "size":{
              "width":400,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd7adf378be14c08aea8df5fd5e3c6af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71da66a02cc6433e8e989f94727b290c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"a4e482b78d4e4d39a65d461f4fd27410",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8cac65af5cce4f3bb368e7a6d546b6d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"e55f002ab17640828dd5dba164b5c491",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"600bf4b25fd841cbb616ac54eac5b42c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"c83575503a2a4c0d974cb98b887be25d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05c721ade50646259dd266fbd1ab3029",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"084a7e0630d148dca64879bca4304a2f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e1b9035715044d890c8f7a7f2c695c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"6cbf5df9de544601819cae38a78ed2a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"733243d80d1e4ca3a4ad19c5c30d20d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"935e1b1751b4444db7c31b8b49987c9c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5e8bc4c19e3d46dea56e5b0b427d3251",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"17bbbd9f408047738a3764aa2f8409ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0bcc4b7e0414804b612be312c58260b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"436060051b5c49ca95cbc9da59f26eab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6c7038e8c1548ee800ec2f5c0bce6a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"b6f69bb00051437ea5404a7562a8685f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63c4e0cb045e45a38b243f6e6554d280",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u50.png"}},
{
              "id":"e44e99d64cb14d8caaf9178e340d7f74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"879e551f3599410e935796693cf2ee7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u50.png"}},
{
              "id":"05b889592cbf450da83196cc9d64772d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"efd562da78714527bdf2ab6372c0eb6e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u50.png"}},
{
              "id":"0240759a8e4f4cff819119ace4c3ffcb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"600058bae2ca47d1b71643a7982ec67c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"be4e175285d14c71b1b4346b0f14adc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"875e08988f674b9c81e1be431a6d45fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"fdc5632a6e0844789d91765311e33eb4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d256df9d9d2e41829363d0b36292f085",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u18.png"}},
{
              "id":"0ff8bf5826544c159d4e67bb243a02b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"295a05f7de174a01bfddea6f46fd7b76",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u24.png"}},
{
              "id":"ac65bf296f9d409eb418cefab6e5440a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d21d6ec59c4d41159e584d10f956eb28",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u24.png"}},
{
              "id":"4e6a8cc55321484191a9b6b12f77c8c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7323129da8a547b8917d56d66ff029bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u24.png"}},
{
              "id":"5bbf0bbd84db453e98c081ba3a79360e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc3cae3cfd7543a69aa2ee0d3828a1b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u24.png"}},
{
              "id":"e32e8d25568f4260a70d3a1c54703820",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2734dd30c816435f97749d06aa25091d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/search_course/u56.png"}}]},
{
          "id":"a31c4e6ea8de4424b9d6b2e1dcf7e3f5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":228},
            "size":{
              "width":100,
              "height":32}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "71774aee331145c7a618dcb567e2c1a8":{
      "scriptId":"u0"},
    "4b4c9cb5db974088b7b78bdeec30ad22":{
      "scriptId":"u1"},
    "6d6a21c0cb8f4d43ac8d9aed73ca5014":{
      "scriptId":"u2"},
    "d21fcf76ed6a4ce2a9d897c50561d895":{
      "scriptId":"u3"},
    "9260faaec67d4fb28f3c9a338fbf893f":{
      "scriptId":"u4"},
    "416b8f194c174fe4a2b623ab5e6ad9bb":{
      "scriptId":"u5"},
    "563ba3247d4347359f15a5ad415e6b6e":{
      "scriptId":"u6"},
    "8c373f42e54b428c977c15ebe65a9ce8":{
      "scriptId":"u7"},
    "1b18ce2eb11c4890a21aef6f0743b683":{
      "scriptId":"u8"},
    "cd1b884809624d55b21c1967e97077e1":{
      "scriptId":"u9"},
    "db18cdbdd03d461d94ad863ddd42bf73":{
      "scriptId":"u10"},
    "208d7a6d8ddf48e6b567ca535be57a69":{
      "scriptId":"u11"},
    "60565e2f791d49c0b85e68c8528f8852":{
      "scriptId":"u12"},
    "a3c210d689844f1699bd627c1de15827":{
      "scriptId":"u13"},
    "9dee6b7d59e142d48ad012dfd58a3ac9":{
      "scriptId":"u14"},
    "05f4dd151b704e7bbab2d8a27385e9ea":{
      "scriptId":"u15"},
    "2340bc73302b49748c6af285b57684ea":{
      "scriptId":"u16"},
    "3eaa9cfb4687463497b36b1b015e78a3":{
      "scriptId":"u17"},
    "dd7adf378be14c08aea8df5fd5e3c6af":{
      "scriptId":"u18"},
    "71da66a02cc6433e8e989f94727b290c":{
      "scriptId":"u19"},
    "c83575503a2a4c0d974cb98b887be25d":{
      "scriptId":"u20"},
    "05c721ade50646259dd266fbd1ab3029":{
      "scriptId":"u21"},
    "935e1b1751b4444db7c31b8b49987c9c":{
      "scriptId":"u22"},
    "5e8bc4c19e3d46dea56e5b0b427d3251":{
      "scriptId":"u23"},
    "0ff8bf5826544c159d4e67bb243a02b9":{
      "scriptId":"u24"},
    "295a05f7de174a01bfddea6f46fd7b76":{
      "scriptId":"u25"},
    "a4e482b78d4e4d39a65d461f4fd27410":{
      "scriptId":"u26"},
    "8cac65af5cce4f3bb368e7a6d546b6d9":{
      "scriptId":"u27"},
    "084a7e0630d148dca64879bca4304a2f":{
      "scriptId":"u28"},
    "2e1b9035715044d890c8f7a7f2c695c7":{
      "scriptId":"u29"},
    "17bbbd9f408047738a3764aa2f8409ff":{
      "scriptId":"u30"},
    "d0bcc4b7e0414804b612be312c58260b":{
      "scriptId":"u31"},
    "ac65bf296f9d409eb418cefab6e5440a":{
      "scriptId":"u32"},
    "d21d6ec59c4d41159e584d10f956eb28":{
      "scriptId":"u33"},
    "0240759a8e4f4cff819119ace4c3ffcb":{
      "scriptId":"u34"},
    "600058bae2ca47d1b71643a7982ec67c":{
      "scriptId":"u35"},
    "be4e175285d14c71b1b4346b0f14adc6":{
      "scriptId":"u36"},
    "875e08988f674b9c81e1be431a6d45fd":{
      "scriptId":"u37"},
    "fdc5632a6e0844789d91765311e33eb4":{
      "scriptId":"u38"},
    "d256df9d9d2e41829363d0b36292f085":{
      "scriptId":"u39"},
    "4e6a8cc55321484191a9b6b12f77c8c3":{
      "scriptId":"u40"},
    "7323129da8a547b8917d56d66ff029bf":{
      "scriptId":"u41"},
    "e55f002ab17640828dd5dba164b5c491":{
      "scriptId":"u42"},
    "600bf4b25fd841cbb616ac54eac5b42c":{
      "scriptId":"u43"},
    "6cbf5df9de544601819cae38a78ed2a6":{
      "scriptId":"u44"},
    "733243d80d1e4ca3a4ad19c5c30d20d8":{
      "scriptId":"u45"},
    "436060051b5c49ca95cbc9da59f26eab":{
      "scriptId":"u46"},
    "f6c7038e8c1548ee800ec2f5c0bce6a8":{
      "scriptId":"u47"},
    "5bbf0bbd84db453e98c081ba3a79360e":{
      "scriptId":"u48"},
    "bc3cae3cfd7543a69aa2ee0d3828a1b9":{
      "scriptId":"u49"},
    "b6f69bb00051437ea5404a7562a8685f":{
      "scriptId":"u50"},
    "63c4e0cb045e45a38b243f6e6554d280":{
      "scriptId":"u51"},
    "e44e99d64cb14d8caaf9178e340d7f74":{
      "scriptId":"u52"},
    "879e551f3599410e935796693cf2ee7e":{
      "scriptId":"u53"},
    "05b889592cbf450da83196cc9d64772d":{
      "scriptId":"u54"},
    "efd562da78714527bdf2ab6372c0eb6e":{
      "scriptId":"u55"},
    "e32e8d25568f4260a70d3a1c54703820":{
      "scriptId":"u56"},
    "2734dd30c816435f97749d06aa25091d":{
      "scriptId":"u57"},
    "a31c4e6ea8de4424b9d6b2e1dcf7e3f5":{
      "scriptId":"u58"}}});