$axure.loadCurrentPage({
  "url":"search_score.html",
  "generationDate":new Date(1528272927260.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"04ffde126ded4deb925b9f8b318d65bf",
    "type":"Axure:Page",
    "name":"search_score",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c487a831b5cd45a2b0afe1b7df154aba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7f7aa221394a05b668095961f19e3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"695a81132c9a4118b67818c0a0f7f3a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":32},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af198a39e1544290b8e050ca6fa1d974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":32},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60a5213cf1bf4e8891c5661fda2e7e9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aed31a8832b476fbf2aecfd81e666d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"b55174a430ba458d9e3726f9b771eb06",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffe2eb3185484a088cb647b4f0f844e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05653e3ddbad406495b32954f0570471",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"7e1f5a7491e84e8599381557be0ec91c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":210},
            "size":{
              "width":710,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99d6c33fa8474d44b37262fbb7f83d00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":210},
                "size":{
                  "width":710,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u9.png"}},
{
          "id":"47b6f3229b2d4c4c964ed1513d334996",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":228},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
}},
{
          "id":"ca01bc4e1d484f8ba1e44c9a6f79dee9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":228},
            "size":{
              "width":140,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d04b924428845048d88e45196cc5f41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":228},
                "size":{
                  "width":140,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u12.png"}},
{
          "id":"01da6f533f6b4aae94e3430c4ae01a03",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":270},
            "size":{
              "width":710,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search_score/u14_line.png"}},
{
          "id":"7e8de5c149154f0c816997a7eab6f237",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":310},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a1d768c1cc94186962e10ea41fefbe4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":310},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"cd34451e558444cba045db708df7acdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":370},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a11dfa70da749c3bdb5a0154edbe8bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":370},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"ac5ccb8e1dd04be5935a93d2ae93f126",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":430},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413553a3f3a849c18fa4100f7a73b8ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":430},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"a1246da19fea4898876e10ff7e86f39a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":310},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03efd7c244bb4972bf3d81caaab35a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":310},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u21.png"}},
{
          "id":"1f7707b35010439db888eb65da12982a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":370},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f706eca72c4cddab60d7f93b1e51b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":370},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u21.png"}},
{
          "id":"2d728c4797d944eb83d6e6464f5302fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":430},
            "size":{
              "width":190,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3cfbdc54aef4686adfac2f0bf7a641e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":430},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u21.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c487a831b5cd45a2b0afe1b7df154aba":{
      "scriptId":"u0"},
    "ea7f7aa221394a05b668095961f19e3a":{
      "scriptId":"u1"},
    "695a81132c9a4118b67818c0a0f7f3a8":{
      "scriptId":"u2"},
    "af198a39e1544290b8e050ca6fa1d974":{
      "scriptId":"u3"},
    "60a5213cf1bf4e8891c5661fda2e7e9a":{
      "scriptId":"u4"},
    "3aed31a8832b476fbf2aecfd81e666d0":{
      "scriptId":"u5"},
    "b55174a430ba458d9e3726f9b771eb06":{
      "scriptId":"u6"},
    "ffe2eb3185484a088cb647b4f0f844e5":{
      "scriptId":"u7"},
    "05653e3ddbad406495b32954f0570471":{
      "scriptId":"u8"},
    "7e1f5a7491e84e8599381557be0ec91c":{
      "scriptId":"u9"},
    "99d6c33fa8474d44b37262fbb7f83d00":{
      "scriptId":"u10"},
    "47b6f3229b2d4c4c964ed1513d334996":{
      "scriptId":"u11"},
    "ca01bc4e1d484f8ba1e44c9a6f79dee9":{
      "scriptId":"u12"},
    "9d04b924428845048d88e45196cc5f41":{
      "scriptId":"u13"},
    "01da6f533f6b4aae94e3430c4ae01a03":{
      "scriptId":"u14"},
    "7e8de5c149154f0c816997a7eab6f237":{
      "scriptId":"u15"},
    "4a1d768c1cc94186962e10ea41fefbe4":{
      "scriptId":"u16"},
    "cd34451e558444cba045db708df7acdd":{
      "scriptId":"u17"},
    "1a11dfa70da749c3bdb5a0154edbe8bf":{
      "scriptId":"u18"},
    "ac5ccb8e1dd04be5935a93d2ae93f126":{
      "scriptId":"u19"},
    "413553a3f3a849c18fa4100f7a73b8ee":{
      "scriptId":"u20"},
    "a1246da19fea4898876e10ff7e86f39a":{
      "scriptId":"u21"},
    "03efd7c244bb4972bf3d81caaab35a34":{
      "scriptId":"u22"},
    "1f7707b35010439db888eb65da12982a":{
      "scriptId":"u23"},
    "a4f706eca72c4cddab60d7f93b1e51b2":{
      "scriptId":"u24"},
    "2d728c4797d944eb83d6e6464f5302fa":{
      "scriptId":"u25"},
    "d3cfbdc54aef4686adfac2f0bf7a641e":{
      "scriptId":"u26"}}});