$axure.loadCurrentPage({
  "url":"set_work.html",
  "generationDate":new Date(1528272927390.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"167180eca7ae4a4bb74a9b9bc8ce9a3e",
    "type":"Axure:Page",
    "name":"set_work",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c9d65ae3005f42ab92deb1d4468d5095",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a4a04c8a027449cb9ad3e39af7a5e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"780e91dda88f4473b128b8dd08756859",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":32},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15242ffede7348018d640ad970f6ff02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":32},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be48ca1ac3ee469dadcc69888ff848a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27ed1b0e2b640b893ad3b4b336b26f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"f7bfedc7553a457e9d011c038ad8de17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d808d180f83d40439ce66976ba5b67af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a077f60d710244e08f40bdf5c23e9b36",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"bea7a15e8a2b4e4eb32d568f0e3cb6dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":200},
            "size":{
              "width":600,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef27fc9afa2940e894f6ae9cfe5c0a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":200},
                "size":{
                  "width":600,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/set_work/u9.png"}},
{
          "id":"244232b2fefc4bfda047b15b0fee555a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":230},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"795f8da6d3bd4b7d8f1c9399b56613f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":230},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"a7e21d0d75c642e3b096bd5edd6bf1d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":280},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a1e57153e694b52947e6ff51bf1890a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":280},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"086b7de1901c4f8682c910681a7c3a20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":333},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df7e39f54a8547ce9983f37f4b04fc65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":333},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"ef18328b9ed647f984ae6d72073682a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":385},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f4432ebeab43119599a0e292e86a75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":385},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"fc1429dd35a943e098eb515d92a2718e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":440},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b9147edd60f4b949ab4bbc0020df449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":440},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_score/u15.png"}},
{
          "id":"7494cd544c4b4c37975ae4253388c6b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":230},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abe0ec814be4421791c6ad421b41cd8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":230},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"963ef96c6314496eb5495e696d3790e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":280},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b372f5510c441599ae2f9eb34c6ef4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":280},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"305aebe0c5d74a91a8bd7268cde9fc7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":333},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c04b00d97bfd490cb87b17115dec013f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":333},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"b87fb2657d124b768410a7e0c82eccc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":385},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10385b09a2c74ea697b0a49a2fcf0a5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":385},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"3c64f98445d647c4bcc2a7583c90913c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":440},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"667615e860a54d34a3ec24c0b9608793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":440},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"da2db6a8d685496a93401fbac6a788d4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5579bc7c0c094298b2445f256bdd0752",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c9d65ae3005f42ab92deb1d4468d5095":{
      "scriptId":"u0"},
    "7a4a04c8a027449cb9ad3e39af7a5e2d":{
      "scriptId":"u1"},
    "780e91dda88f4473b128b8dd08756859":{
      "scriptId":"u2"},
    "15242ffede7348018d640ad970f6ff02":{
      "scriptId":"u3"},
    "be48ca1ac3ee469dadcc69888ff848a5":{
      "scriptId":"u4"},
    "f27ed1b0e2b640b893ad3b4b336b26f2":{
      "scriptId":"u5"},
    "f7bfedc7553a457e9d011c038ad8de17":{
      "scriptId":"u6"},
    "d808d180f83d40439ce66976ba5b67af":{
      "scriptId":"u7"},
    "a077f60d710244e08f40bdf5c23e9b36":{
      "scriptId":"u8"},
    "bea7a15e8a2b4e4eb32d568f0e3cb6dc":{
      "scriptId":"u9"},
    "ef27fc9afa2940e894f6ae9cfe5c0a29":{
      "scriptId":"u10"},
    "244232b2fefc4bfda047b15b0fee555a":{
      "scriptId":"u11"},
    "795f8da6d3bd4b7d8f1c9399b56613f6":{
      "scriptId":"u12"},
    "a7e21d0d75c642e3b096bd5edd6bf1d1":{
      "scriptId":"u13"},
    "1a1e57153e694b52947e6ff51bf1890a":{
      "scriptId":"u14"},
    "086b7de1901c4f8682c910681a7c3a20":{
      "scriptId":"u15"},
    "df7e39f54a8547ce9983f37f4b04fc65":{
      "scriptId":"u16"},
    "ef18328b9ed647f984ae6d72073682a1":{
      "scriptId":"u17"},
    "11f4432ebeab43119599a0e292e86a75":{
      "scriptId":"u18"},
    "fc1429dd35a943e098eb515d92a2718e":{
      "scriptId":"u19"},
    "1b9147edd60f4b949ab4bbc0020df449":{
      "scriptId":"u20"},
    "7494cd544c4b4c37975ae4253388c6b5":{
      "scriptId":"u21"},
    "abe0ec814be4421791c6ad421b41cd8e":{
      "scriptId":"u22"},
    "963ef96c6314496eb5495e696d3790e0":{
      "scriptId":"u23"},
    "1b372f5510c441599ae2f9eb34c6ef4d":{
      "scriptId":"u24"},
    "305aebe0c5d74a91a8bd7268cde9fc7d":{
      "scriptId":"u25"},
    "c04b00d97bfd490cb87b17115dec013f":{
      "scriptId":"u26"},
    "b87fb2657d124b768410a7e0c82eccc4":{
      "scriptId":"u27"},
    "10385b09a2c74ea697b0a49a2fcf0a5c":{
      "scriptId":"u28"},
    "3c64f98445d647c4bcc2a7583c90913c":{
      "scriptId":"u29"},
    "667615e860a54d34a3ec24c0b9608793":{
      "scriptId":"u30"},
    "da2db6a8d685496a93401fbac6a788d4":{
      "scriptId":"u31"},
    "5579bc7c0c094298b2445f256bdd0752":{
      "scriptId":"u32"}}});