$axure.loadCurrentPage({
  "url":"get_work.html",
  "generationDate":new Date(1528272927453.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4d128f63b3124c37a92b37575c673bf9",
    "type":"Axure:Page",
    "name":"get_work",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dff5a9c224004b369f43cb78fb7afdc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88f514fed3934796bae24f7b11673ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"0c24afca80c040f597f17b47f4962147",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":32},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2cd11c9b7fd41788f54fee54b0eadfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":32},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89453fef4a9343a4a19567b3b5d9a40e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0959a61d7d8e4a92932ca7502d5dcf14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"8b3e1535905542fca890155733cb8f60",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"372c6e335ac6425cbc6894970fed3f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffccb11d01214aad883b1333bae5f84e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"5e686cd643a84d10b7e8200ecb18395f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":210},
            "size":{
              "width":800,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc13eb999d6b49c7ae4ab2c3b88d9c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":210},
                "size":{
                  "width":800,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/get_work/u9.png"}},
{
          "id":"87b2cf75d1264283be4d8d4835a415f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":230},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a07cf32d85d48b0b955bd46ee94a67c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":230},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_course/u56.png"}},
{
          "id":"6de52c636d484900969dae9fc32295cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":290},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"240dbda3186f418bbbc71fa93c6220e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":290},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_course/u56.png"}},
{
          "id":"d681d395e8024358801bec2c6ebd6ebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":230},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55d63931096e4d529944625a25b93ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":230},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_course/u56.png"}},
{
          "id":"323fb6a89231423dbc9754e4c07ceec5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":290},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e47a4af6ca24b2aa57f60070599405a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":290},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_course/u56.png"}},
{
          "id":"8d92a14158b04d8c808a66288ad50b8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":230},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d6a1332a3514a2794f2db78510831e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":230},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"bdfd098c9e57476fa89458eaf0636e94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":230},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4332f4c7f2e3463aa1cdc46780a47286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":230},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"ed90ff8b46fb4598b13eb0119f6aacf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":290},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c31bff149b140df9e7dd95b215ce925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":290},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"6391ee64d7fb4129978690a7a9ad13cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":290},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43bc678c5eb84edca7483f8e8db5f28b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":290},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"5f203ae74b714585846ae8ae4ef657ad",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":340},
            "size":{
              "width":800,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/get_work/u27_line.png"}},
{
          "id":"e6d5c13485b444b6aab9c90c67ba86f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":375},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67eecdd7cf524d52b53f1fa7c01553e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":375},
                "size":{
                  "width":100,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/get_work/u28.png"}},
{
          "id":"64508ccef80446589f5432f7ed79b1cf",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":375},
            "size":{
              "width":560,
              "height":245}},
          "adaptiveStyles":{
}},
{
          "id":"fd570264bbcb4e33add95af452269cbc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":655},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7a0febacf4e443209e28984442d7e1ca",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":655},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "dff5a9c224004b369f43cb78fb7afdc1":{
      "scriptId":"u0"},
    "88f514fed3934796bae24f7b11673ce3":{
      "scriptId":"u1"},
    "0c24afca80c040f597f17b47f4962147":{
      "scriptId":"u2"},
    "c2cd11c9b7fd41788f54fee54b0eadfa":{
      "scriptId":"u3"},
    "89453fef4a9343a4a19567b3b5d9a40e":{
      "scriptId":"u4"},
    "0959a61d7d8e4a92932ca7502d5dcf14":{
      "scriptId":"u5"},
    "8b3e1535905542fca890155733cb8f60":{
      "scriptId":"u6"},
    "372c6e335ac6425cbc6894970fed3f45":{
      "scriptId":"u7"},
    "ffccb11d01214aad883b1333bae5f84e":{
      "scriptId":"u8"},
    "5e686cd643a84d10b7e8200ecb18395f":{
      "scriptId":"u9"},
    "cc13eb999d6b49c7ae4ab2c3b88d9c17":{
      "scriptId":"u10"},
    "87b2cf75d1264283be4d8d4835a415f8":{
      "scriptId":"u11"},
    "3a07cf32d85d48b0b955bd46ee94a67c":{
      "scriptId":"u12"},
    "6de52c636d484900969dae9fc32295cd":{
      "scriptId":"u13"},
    "240dbda3186f418bbbc71fa93c6220e7":{
      "scriptId":"u14"},
    "d681d395e8024358801bec2c6ebd6ebe":{
      "scriptId":"u15"},
    "55d63931096e4d529944625a25b93ae9":{
      "scriptId":"u16"},
    "323fb6a89231423dbc9754e4c07ceec5":{
      "scriptId":"u17"},
    "9e47a4af6ca24b2aa57f60070599405a":{
      "scriptId":"u18"},
    "8d92a14158b04d8c808a66288ad50b8a":{
      "scriptId":"u19"},
    "9d6a1332a3514a2794f2db78510831e5":{
      "scriptId":"u20"},
    "bdfd098c9e57476fa89458eaf0636e94":{
      "scriptId":"u21"},
    "4332f4c7f2e3463aa1cdc46780a47286":{
      "scriptId":"u22"},
    "ed90ff8b46fb4598b13eb0119f6aacf7":{
      "scriptId":"u23"},
    "7c31bff149b140df9e7dd95b215ce925":{
      "scriptId":"u24"},
    "6391ee64d7fb4129978690a7a9ad13cf":{
      "scriptId":"u25"},
    "43bc678c5eb84edca7483f8e8db5f28b":{
      "scriptId":"u26"},
    "5f203ae74b714585846ae8ae4ef657ad":{
      "scriptId":"u27"},
    "e6d5c13485b444b6aab9c90c67ba86f4":{
      "scriptId":"u28"},
    "67eecdd7cf524d52b53f1fa7c01553e7":{
      "scriptId":"u29"},
    "64508ccef80446589f5432f7ed79b1cf":{
      "scriptId":"u30"},
    "fd570264bbcb4e33add95af452269cbc":{
      "scriptId":"u31"},
    "7a0febacf4e443209e28984442d7e1ca":{
      "scriptId":"u32"}}});