$axure.loadCurrentPage({
  "url":"search_msg.html",
  "generationDate":new Date(1528272927074.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3418140bfbad4e7487282d86e5d21880",
    "type":"Axure:Page",
    "name":"search_msg",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a3b407078f6a4529a3b9c394475da378",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":300,
              "y":0},
            "size":{
              "width":800,
              "height":100},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a6f2156ddb9409eb67dfe433f15af45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":800,
                  "height":100},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u0.png"}},
{
          "id":"eb7ed857214048d2bd222b93b4672ad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":32},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b5a80b41d647138946f48fd7d4ba3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":32},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7376ebaf5894c9085822c9988fa5e21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":99},
            "size":{
              "width":800,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24673f5798c84dae86fea33c2d13d463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":99},
                "size":{
                  "width":800,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stu_index/u28.png"}},
{
          "id":"112e962415174fdba5897b88d7f7fa78",
          "label":"",
          "type":"buttonShape",
          "styleType":"h3",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":109},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8754de3a0ba24987b2192213951e95af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":109},
                "size":{
                  "width":76,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2177ef562c704ebb83a12906e7008bcb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":99},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"b86dae94009a484c891337d9735d3df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":230},
            "size":{
              "width":630,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61d0444e78b8498da1dfd5bf2913f55d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":230},
                "size":{
                  "width":630,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u9.png"}},
{
          "id":"c22cec6aaf5b435dab0b2cd841a12428",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":410,
              "y":260},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e02e4db3182446afafb704c8897eecd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":260},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u11.png"}},
{
          "id":"2f5a855d6cf5445dbba788865e4dc033",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":260},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b187ecacd14ebeac0c1088acc16dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":260},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"7eca25acb0ea42aba289c9061f514d9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":410,
              "y":300},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85e24a02b1794f2fa2d9b3447275a14d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":300},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u11.png"}},
{
          "id":"72a81e97e85842dd8069966996b5d814",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":410,
              "y":340},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40ead98d58fb4e3fba6e67d50e7f89e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":340},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u11.png"}},
{
          "id":"826882151f3743289f1619327e5f8cbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":410,
              "y":380},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"214e006ffe974dd7a13b6055a70fbe81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":380},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u11.png"}},
{
          "id":"beac6b675cb941d883285cdbd68e40ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":410,
              "y":420},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"465157024e8949d3a08e21b16b584d47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":420},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u11.png"}},
{
          "id":"c0a56be92f344c3796ebf5361971a81b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":300},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dae5659dc34c4c84b5c700ecfa37e62d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":300},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"02f4230165034f02aa558e1ca48dc3be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":340},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f785d06e7d24f7597e3504fd87174c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":340},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"e04ea5989d164dd2a2c88bd4027c3fd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":380},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da0b14a0425c4fd1af54f4e7496d1fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":380},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}},
{
          "id":"66b431f2853b486b9030116632415813",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":420},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db0b40a4d7cf424c95d5b03cf557f00f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":420},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search_msg/u13.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a3b407078f6a4529a3b9c394475da378":{
      "scriptId":"u0"},
    "5a6f2156ddb9409eb67dfe433f15af45":{
      "scriptId":"u1"},
    "eb7ed857214048d2bd222b93b4672ad7":{
      "scriptId":"u2"},
    "08b5a80b41d647138946f48fd7d4ba3f":{
      "scriptId":"u3"},
    "b7376ebaf5894c9085822c9988fa5e21":{
      "scriptId":"u4"},
    "24673f5798c84dae86fea33c2d13d463":{
      "scriptId":"u5"},
    "112e962415174fdba5897b88d7f7fa78":{
      "scriptId":"u6"},
    "8754de3a0ba24987b2192213951e95af":{
      "scriptId":"u7"},
    "2177ef562c704ebb83a12906e7008bcb":{
      "scriptId":"u8"},
    "b86dae94009a484c891337d9735d3df3":{
      "scriptId":"u9"},
    "61d0444e78b8498da1dfd5bf2913f55d":{
      "scriptId":"u10"},
    "c22cec6aaf5b435dab0b2cd841a12428":{
      "scriptId":"u11"},
    "e02e4db3182446afafb704c8897eecd2":{
      "scriptId":"u12"},
    "2f5a855d6cf5445dbba788865e4dc033":{
      "scriptId":"u13"},
    "56b187ecacd14ebeac0c1088acc16dab":{
      "scriptId":"u14"},
    "7eca25acb0ea42aba289c9061f514d9d":{
      "scriptId":"u15"},
    "85e24a02b1794f2fa2d9b3447275a14d":{
      "scriptId":"u16"},
    "72a81e97e85842dd8069966996b5d814":{
      "scriptId":"u17"},
    "40ead98d58fb4e3fba6e67d50e7f89e7":{
      "scriptId":"u18"},
    "826882151f3743289f1619327e5f8cbf":{
      "scriptId":"u19"},
    "214e006ffe974dd7a13b6055a70fbe81":{
      "scriptId":"u20"},
    "beac6b675cb941d883285cdbd68e40ad":{
      "scriptId":"u21"},
    "465157024e8949d3a08e21b16b584d47":{
      "scriptId":"u22"},
    "c0a56be92f344c3796ebf5361971a81b":{
      "scriptId":"u23"},
    "dae5659dc34c4c84b5c700ecfa37e62d":{
      "scriptId":"u24"},
    "02f4230165034f02aa558e1ca48dc3be":{
      "scriptId":"u25"},
    "8f785d06e7d24f7597e3504fd87174c3":{
      "scriptId":"u26"},
    "e04ea5989d164dd2a2c88bd4027c3fd6":{
      "scriptId":"u27"},
    "da0b14a0425c4fd1af54f4e7496d1fc3":{
      "scriptId":"u28"},
    "66b431f2853b486b9030116632415813":{
      "scriptId":"u29"},
    "db0b40a4d7cf424c95d5b03cf557f00f":{
      "scriptId":"u30"}}});